services:
  web-service:
    image: "aus-web-service"
    build:
      context: ./web-service
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./web-service:/web-service

  frontend:
    image: "aus-frontend"
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
    depends_on:
      - web-service
