
### 
# @name auth
POST  https://{{authHost}}/oauth/token
Content-Type: application/json

{
  "client_id": "{{client_id}}",
  "client_secret": "{{client_secret}}",
  "audience": "{{audience}}",
  "grant_type": "client_credentials"
}

###
@JWT = {{auth.response.body.access_token}}

###
GET {{protocol}}://{{host}}:{{portBack}}/api/private/offre/1
Content-Type: application/json
authorization: Bearer {{JWT}}


###
GET {{protocol}}://{{host}}:{{portBack}}/api/public/offre/1
Content-Type: application/json
authorization: Bearer {{JWT}}
