// localhost  
@protocol = http
@host = localhost
@portBack = 3000

### 
# @name auth
POST  https://{{authHost}}/oauth/token
Content-Type: application/json

{
  "client_id": "{{client_id}}",
  "client_secret": "{{client_secret}}",
  "audience": "{{audience}}",
  "grant_type": "client_credentials"
}

###
@JWT = {{auth.response.body.access_token}}


### API ### 

### PRIVATE ###

### Offre 

###
# @name getOffreById
GET {{protocol}}://{{host}}:{{portBack}}/api/private/offre/14621
Content-Type: application/json
authorization: Bearer {{JWT}}

###
# @name getOffreByIdExtend
GET {{protocol}}://{{host}}:{{portBack}}/api/private/offre/extend/14621
Content-Type: application/json
authorization: Bearer {{JWT}}

###
# @name getAllOffre
GET {{protocol}}://{{host}}:{{portBack}}/api/private/offre/
Content-Type: application/json
authorization: Bearer {{JWT}}

###
# @name countAllOffers
GET {{protocol}}://{{host}}:{{portBack}}/api/private/dashboard/countoffer/
Content-Type: application/json
authorization: Bearer {{JWT}}

###
# @name countOfferByJob
GET {{protocol}}://{{host}}:{{portBack}}/api/private/dashboard/countofferbyjob/
Content-Type: application/json
authorization: Bearer {{JWT}}

###
# @name createOffre
POST {{protocol}}://{{host}}:{{portBack}}/api/private/offre/
Content-Type: application/json
authorization: Bearer {{JWT}}

{
  "secteur_id": 7,
  "metier_id": 10,
  "titre_emploi": "titre_emploi",
  "entreprise": "entreprise",
  "lieu": "lieu",
  "description_courte": "description_courte",
  "contrat": "contrat",
  "type_contrat": "type_contrat",
  "description": "description",
  "commune_id": "80001"
}

###
# @name createOffreMany
POST {{protocol}}://{{host}}:{{portBack}}/api/private/offre/many
Content-Type: application/json
authorization: Bearer {{JWT}}

[
  {
    "secteur_id": 7,
    "metier_id": 10,
    "titre_emploi": "titre_emploi",
    "entreprise": "entreprise",
    "lieu": "lieu",
    "description_courte": "description_courte",
    "contrat": "contrat",
    "type_contrat": "type_contrat",
    "description": "description",
    "commune_id": "80001"
  },
  {
    "secteur_id": 7,
    "metier_id": 10,
    "titre_emploi": "titre_emploi",
    "entreprise": "entreprise",
    "lieu": "lieu",
    "description_courte": "description_courte",
    "contrat": "contrat",
    "type_contrat": "type_contrat",
    "description": "description",
    "commune_id": "80001"
  }
]

###
# @name deleteById
DELETE  {{protocol}}://{{host}}:{{portBack}}/api/private/offre/14623
Content-Type: application/json
authorization: Bearer {{JWT}}

###
# @name updateOffre
PATCH {{protocol}}://{{host}}:{{portBack}}/api/private/offre/14621
Content-Type: application/json
authorization: Bearer {{JWT}}

{
  "secteur_id": 32,
  "metier_id": 10,
  "titre_emploi": "titre_emploiupdate"
}


### PUBLIC ###

###

###
GET {{protocol}}://{{host}}:{{portBack}}/api/public/offre/1
Content-Type: application/json
authorization: Bearer {{JWT}}
